### ISSUE TITLE
TODO List for Sunday, October 18th

### ISSUE THREAD

**Issue by redxe** [colinthomas-z80/automated-access-control#1]
# TODO List
 - [x] Complete Business Requirements
 - [x] Complete Requirements
 - [x] Complete TechStack
 - [x] Map requirements to business requirements
 - [x] Add paragraphs to each entry in Design/BusinessRequirements.md (discuss with Kyle)
 - [x] Complete Prototype in Adobe XD
 - [x] Complete Use Cases
 -  [x] Assign priorities to each of the requirements
 - [x] Record prototype and upload to YouTube
 - [x] Complete Domain Model
 - [x] Complete First Iteration Features
